publish:
  image: python:latest
  artifacts:
    paths:
      - public
  before_script:
    - pip install pipenv
    - which pip
    - which python
  script:
    - "pipenv --python `which python` run make publish"
