pages:
  stage: build
  image: python:3.6
  artifacts:
    paths:
      - public
  only:
    - master
  before_script:
    - pip install pipenv
    - which pip
    - which python
  script:
    - "pipenv install"
    - "pipenv run make publish"

salt:
  stage: deploy
  image: registry.gitlab.com/spirostack/spiro-deploy:master
  only:
    - master
  script:
    spiro-deploy astraluma prod --highstate --artifact=public
