publish:
  image: python:latest
  artifacts:
    paths:
      - public
  before_script:
    - pip install pipenv
    - which pip
    - which python
  script:
    - "pipenv install"
    - "pipenv run make publish"
